### ISSUE TITLE
License change to AGPL

### ISSUE THREAD

**Issue by AndrewVSutherland** [AndrewVSutherland/psetpartners#351]
@jsu27 @edgarcosta @tckmn David Roe and I would like to change the license to AGPL from GPL.

As explained by MongoDB (see the quote below), AGPL prevents licensees from offering the software as a service running on a site that whose source code is not open source (contrary to the copyleft philosophy underlying GPL):

`Our goal with using AGPL is to preserve the concept of copyleft with MongoDB. With traditional GPL, copyleft was associated with the concept of distribution of software. The problem is that nowadays, distribution of software is rare: things tend to run in the cloud. AGPL fixes this “loophole” in GPL by saying that if you use the software over a network, you are bound by the copyleft. Other than that, the license is virtually the same as GPL v3.`

<s>The psycodict library we depend on is going to move to AGPL, so I think it makes sense for us to do the same.</s>

We need the consent of all contributors to do this, so please post a comment on this issue to indicate whether you agree or disagree.

**Comment by AndrewVSutherland** [comment]
Correction: psycodict isn't necessarily using AGPL (and there are reasonable arguments for it to use a more permissive license, since it is an internal component not a complete application), but I think it makes sense for pset partners to go with AGPL in any case.

**Comment by roed314** [comment]
Fine with me.

**Comment by edgarcosta** [comment]
Agree

**Comment by jsu27** [comment]
Agree.

**Comment by tckmn** [comment]
:+1:

**Comment by AndrewVSutherland** [comment]
The LICENSE file has now been updated to AGPL -- thanks everyone!
