### ISSUE TITLE
Add transactioning

### ISSUE THREAD

**Issue by AndrewVSutherland** [AndrewVSutherland/psetpartners#72]
Currently database updates made in save_student are not transactioned, even though they may involve modifications to multiple tables.  This needs to be addressed before we go live.

**Comment by roed314** [comment]
You should be able to use `with DelayCommit` for this.  See examples in `lmfdb/backend/table.py`

**Comment by AndrewVSutherland** [comment]
Thanks, and I see this is in psycodict; it should be straight-forward to add this (all the database updates are in student.py and will be easy to wrap).
